### ISSUE TITLE
Bu kodda duzelisler olmalidir ..😁

### ISSUE THREAD

**Issue by ElcinQuliyev** [askherov/shopiphone#1]
https://github.com/askherov/shopiphone/blame/4e9024e19d091d5b5b8cb035c1993f2187601953/shopiphone/phones/models.py#L26

**Comment by ElcinQuliyev** [comment]
Coda Baxilar

**Comment by askherov** [comment]
salam duzeltdim 
![image](https://github.com/askherov/shopiphone/assets/157063910/2716d7fa-153f-4141-a690-56cd7ddd3d5a)

**Comment by ElcinQuliyev** [comment]
> https://github.com/askherov/shopiphone/blame/4e9024e19d091d5b5b8cb035c1993f2187601953/shopiphone/phones/models.py#L26
